version: "3.8"

services:
  plants-app-dev:
    build:
      context: ./plants/app
      dockerfile: Dockerfile.dev
    image: plantdex_plants-app-dev
    container_name: plantdex_plants-app-dev
    env_file:
      - plants/.env
    ports:
      - "127.0.0.1:4040:4040"

  plants-db-dev:
    build:
      context: ./plants/db
      dockerfile: Dockerfile.dev
    image: plantdex_plants-db-dev
    container_name: plantdex_plants-db-dev
    volumes:
      - plants-db:/data/db

  plants-proxy-dev:
    build:
      context: ./plants/proxy
      dockerfile: Dockerfile.dev
    image: plantdex_plants-proxy-dev
    container_name: plantdex_plants-proxy-dev
    environment:
      - ENVOY_UID=777
      - ENVOY_GID=777
    ports:
      - "127.0.0.1:9901:9901"
      - "127.0.0.1:10000:10000"

  web-app-dev:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    image: plantdex_web-app-dev
    container_name: plantdex_web-app-dev
    env_file:
      - web/.env
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./web:/usr/src/app

volumes:
  plants-db:
