name: Deploy API gateway

on:
  push:
    branches: [master]
    paths:
      - "api-gateway/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: api-gateway

jobs:
  build-push-proxy:
    name: Build and push the proxy Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master
      - name: Build image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/plantdex_"${{ secrets.API_GATEWAY_NAME }}":prod -f Dockerfile.prod ./
      - name: Log in
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push image
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/plantdex_"${{ secrets.API_GATEWAY_NAME }}":prod

  deploy:
    name: Deploy the Docker image to DigitalOcean
    runs-on: ubuntu-latest
    needs: [build-push-proxy]
    steps:
      - name: Log in and deploy image
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          API_GATEWAY_NAME: ${{ secrets.API_GATEWAY_NAME }}
        with:
          host: ${{ secrets.DIGITALOCEAN_PLANTS_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          envs: DOCKER_USERNAME, API_GATEWAY_NAME
          script: |
            docker pull $DOCKER_USERNAME/plantdex_$API_GATEWAY_NAME:prod
            docker network create --internal plants
            docker rm -f $API_GATEWAY_NAME
            docker run -d -p 443:10000 --network plants --restart unless-stopped -v ~/tls:/etc/tls -e ENVOY_UID=777 -e ENVOY_GID=777 --name $API_GATEWAY_NAME $DOCKER_USERNAME/plantdex_$API_GATEWAY_NAME:prod
            docker network connect bridge $API_GATEWAY_NAME
            docker system prune -f --volumes
